version: "3.8"

services:
    # web:
    #     build:
    #         context: .
    #         dockerfile: development.Dockerfile
    #     command: uvicorn epseon_gui.main:app --host 0.0.0.0 --port 8000
    #     volumes:
    #         - .:/code
    #     ports:
    #         - 2137:8000
    #     depends_on:
    #         - db
    backend:
        container_name: epseon-backend
        restart: always
        build:
            dockerfile: Dockerfile
            context: .
        environment:
            - DB_USER=postgres
            - DB_PASSWORD=s3cr3tp45w0rd
            - DB_HOST=postgres
            - DB_PORT=5432
            - DATABASE=postgres
        ports:
            - "2137:8000"
        expose:
            - 5432
        depends_on:
            - postgres

    postgres:
        container_name: epseon-backend-postgres
        image: postgres:alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=s3cr3tp45w0rd
        ports:
            - 5432:5432
        expose:
            - 5432
        volumes:
            - postgres-volume:/var/lib/postgresql/data

volumes:
    postgres-volume:
        name: epseon-volume
