version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: uvicorn epseon_gui.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - 2137:8000
    depends_on:
      - db
  db:
    image: docker.io/postgres:16.0
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./.env

volumes:
  postgres_data:
